services:
    hispace:
        image: hispace/p2p:latest
        container_name: hispace
        hostname: hispace
        restart: unless-stopped
        ports:
            - '${PORT}:${PORT}'
        volumes:
            - ./.env:/src/.env:ro
            # Rebranding:
            # - ./app/src/config.js:/src/app/src/config.js:ro
            # Optional volumes for real-time updates:
            # - ./app/:/src/app/:ro
            # - ./public/:/src/public/:ro
# Uncomment below, remove "ports:" section above and configure labels as
# needed for LetsEncrypt TLS certificates with Traefik.
# See https://doc.traefik.io/traefik/user-guides/docker-compose/basic-example/
#   expose:
#     - 3000
#   labels:
#     - "traefik.enable=true"
#     - "traefik.http.routers.hispace.rule=Host(`hispace.example.com`)"
#     - "traefik.http.routers.hispace.entrypoints=websecure"
#     - "traefik.http.routers.hispace.tls.certresolver=myresolver"
#     - "traefik.http.services.hispace.loadbalancer.server.port=3000"
